version: '3'
services:
  web:
    image: javaweb-docker:1.2
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - ENV=QA
    ports:
      - 8080:8080
    depends_on:
      - redis-db
  redis-db:
    image: redis:5.0-rc
    environment:
      - ENV=QA
    volumes:
      - C:\workspace\Kubernetes\docker-data\redis:/data:rw
    ports:
      - 6379:6379

# set COMPOSE_CONVERT_WINDOWS_PATHS=1
# docker-compose -p javaweb up -d
# docker-compose -p javaweb down
# docker container exec -it javaweb_web_1 bash
# docker container exec -it javaweb_redis-db_1 bash
# docker container logs javaweb_redis-db_1
