apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: qa
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 #
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.3
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: qa
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8000
    nodePort: 8000
    targetPort: 80