version: '3'
services:
  jenkins:
    image: jenkins:2.60.3
    hostname: jenkins
    domainname: coreit
    environment:
      - ENV=COREIT
    volumes:
      - /shares/jenkins/jenkins_home:/var/jenkins_home
      - /shares/jenkins/docker_cert_path:/var/docker_cert_path
    ports:
      - 8082:8080
    links:
      - nexus
    restart: unless-stopped
    healthcheck:
      test: curl -s http://localhost:8080 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
  nexus:
    image: sonatype/nexus3:3.13.0
    hostname: nexus
    domainname: coreit
    # environment:
      # - MAX_HEAP=1024m
    volumes:
      # - /shares/nexus-data:/nexus-data
      - nexus_data:/nexus-data
    ports:
      - 8081:8081
      - 8083:8083
    restart: unless-stopped
    healthcheck:
      test: curl -s http://localhost:8081 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
  # rancher:
    # image: rancher/rancher:v2.0.8
    # hostname: rancher
    # domainname: coreit
    # volumes:
      # - rancher_data:/var/lib/rancher
    # ports:
      # - 80:80
      # - 443:443
    # restart: unless-stopped
    
  # registry:
    # image: registry:2.6
    # hostname: registry
    # domainname: coreit
    # environment:
      # - ENV=COREIT
    # volumes:
      # - /shares/registry/data:/var/lib/registry
    # ports:
      # - 5000:5000
    # restart: unless-stopped
volumes:
  nexus_data:
  # rancher_data: