version: '3'
services:
  jenkins:
    image: jenkins
    hostname: jenkins
    domainname: coreit
    environment:
      - ENV=COREIT
    volumes:
      - /shares/jenkins/jenkins_home:/var/jenkins_home
      - /shares/jenkins/docker_cert_path:/var/docker_cert_path
    ports:
      - 8082:8080
    links:
      # - registry
      - nexus
    restart: unless-stopped
  # registry:
    # image: registry:2.6
    # hostname: registry
    # domainname: coreit
    # environment:
      # - ENV=COREIT
    # volumes:
      # - /shares/registry/data:/var/lib/registry
    # ports:
      # - 5000:5000
    # restart: unless-stopped
  nexus:
    image: sonatype/nexus3
    hostname: nexus
    domainname: coreit
    # environment:
      # - MAX_HEAP=1024m
    volumes:
      - /shares/nexus-data:/nexus-data
    ports:
      - 8081:8081
      - 8083:8083
    restart: unless-stopped



  elk-elasticsearch-1:
    # grep vm.max_map_count /etc/sysctl.conf
    # sudo sysctl -w vm.max_map_count=262144
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    hostname: elk-elasticsearch-1
    domainname: coreit
    environment:
      - ENV=COREIT
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elk-elasticsearch-1,elk-elasticsearch-2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /shares/elk/elasticsearch/node1:/usr/share/elasticsearch/data
      #- /shares/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
  elk-elasticsearch-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    hostname: elk-elasticsearch-2
    domainname: coreit
    environment:
      - ENV=COREIT
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elk-elasticsearch-1,elk-elasticsearch-2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /shares/elk/elasticsearch/node2:/usr/share/elasticsearch/data
    # ports:
      # - 9200:9200
    links:
      - elk-elasticsearch-1
      #- elk-elasticsearch-2
  elk-kibana-1:
    image: docker.elastic.co/kibana/kibana:6.3.2
    hostname: elk-kibana-1
    domainname: coreit
    environment:
      - ENV=COREIT
      - server.host="0.0.0.0"
      - ELASTICSEARCH_URL="http://elk-elasticsearch-1:9200"
    # volumes:
      # - /shares/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elk-elasticsearch-1
  # elk-kibana-2:
    # image: docker.elastic.co/kibana/kibana:6.3.2
    # hostname: elk-kibana-2
    # domainname: coreit
    # environment:
      # - ENV=COREIT
      # - server.host="0.0.0.0"
      # - ELASTICSEARCH_URL="http://elk-elasticsearch-2:9200"
    # # volumes:
      # # - /shares/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    # ports:
      # - 5601:5601
    # depends_on:
      # - elk-elasticsearch-2
  elk-logstash-1:
    image: docker.elastic.co/logstash/logstash:6.3.2
    hostname: elk-logstash-1
    domainname: coreit
    environment:
      - ENV=COREIT
      - xpack.monitoring.elasticsearch.url=http://elk-elasticsearch-1:9200
      - config.reload.automatic=true
    volumes:
      - /shares/elk/logstash/pipeline:/usr/share/logstash/pipeline
      # - /shares/elk/logstash/node1:/usr/share/logstash/data
    depends_on:
      - elk-elasticsearch-1
      - elk-elasticsearch-2
  elk-filebeat-1:
    image: docker.elastic.co/beats/filebeat:6.3.2
    hostname: elk-filebeat-1
    domainname: coreit
    environment:
      - ENV=COREIT
    volumes:
      - /shares/elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elk-logstash-1
