version: '3'
services:
  tomcat-1:
    image: javaweb-docker:${APP_VERSION}
    hostname: tomcat-1
    domainname: internal
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - APP_LOG_PATH=/data
      - ENV=
    ports:
      - 8080:8080
    volumes:
      - /shares/tomcat/logs:/data
    depends_on:
      - redis-db
    restart: unless-stopped
    healthcheck:
      test: curl -s http://localhost:8080 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
  redis-db:
    image: redis:4.0.11
    hostname: redis-db
    domainname: internal
    environment:
      - ENV=
    ports:
      - 6379:6379
    restart: unless-stopped
    healthcheck:
      #test: ping="$(redis-cli -h localhost ping)"; if [[ "$ping" == 'PONG' ]]; then echo 0; else echo 1; fi
      test: redis-cli -h localhost ping
      interval: 30s
      timeout: 10s
      retries: 5
    
  # cadvisor:
    # image: google/cadvisor
    # hostname: cadvisor
    # domainname: internal
    # ports:
      # - 9080:8080
    # volumes:
      # - /:/rootfs:ro
      # - /var/run:/var/run:rw
      # - /sys:/sys:ro
      # - /var/lib/docker/:/var/lib/docker:ro
    # restart: unless-stopped
  # sensu-server:
    # image: hiroakis/docker-sensu-server
    # hostname: sensu-server
    # domainname: internal
    # ports:
      # - 3000:3000
      # - 4567:4567
      # - 5671:5671
      # - 15672:15672
    # volumes:
      # # - /shares/sensu/check-docker.json:/etc/sensu/conf.d/check-docker.json
      # - /shares/sensu:/etc/sensu/conf.d
  # sensu-client:
    # image: usman/sensu-client
    # hostname: sensu-client
    # domainname: internal
    # privileged: true
    # depends_on:
      # - sensu-server
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      # # - /shares/sensu/load-docker-metrics.sh:/etc/sensu/plugins/load-docker-metrics.sh
      # - /shares/sensu:/etc/sensu/plugins
    # # SENSU_SERVER_IP RABIT_MQ_USER RABIT_MQ_PASSWORD CLIENT_NAME CLIENT_IP
    # command: sensu-server sensu password sensu-client sensu-client
    
